@startuml usecase-diagram

skinparam actorStyle awesome
left to right direction

actor Player

' Sistema
rectangle Game {
    ' Casos de uso
    usecase "Start Game" as UC1
    usecase "Play Turn" as UC2
    usecase "Use Card" as UC3
}

' Relacionamentos
:Player: -- (UC1)
:Player: -- (UC2)
(UC2) <. (UC3) : extend

@enduml