@startuml class-diagram

skinparam ClassAttributeIconSize 0

' Classes principais

class Character {
    - int healthPoints
    - int mana
}

class Card{
    - int manaCost
    - string title
    - string description
}

class Deck{
    - vector<Card*> cards
}


' Relacionamentos

Deck --> Card

@enduml